on: [push]

jobs:
  publish_ubuntu:
    runs-on: ubuntu-latest
    name: publish Ubuntu executable image
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@master
      with: { python-version: 3.8 }
    - name: Install dependencies
      run: python -m pip install -r requirements.txt
    - name: Install GeographicLib
      run: sudo apt-get install -y libgeographic-dev
    - name: Build wheel
      run: python setup.py bdist_wheel
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist-ubuntu
        path: dist/
